// Conteúdo pedagógico para 24 a 30 meses.
// Fontes: marcos CDC "Learn the Signs. Act Early" (revisão 2022), Sociedade Brasileira de Pediatria,
// AAP (co-uso de mídia), literatura sobre "déficit de transferência" e linguagem responsiva.

window.DOMAINS = {
  linguagem: { label: "Linguagem", emoji: "🗣️", color: "#e8b86d" },
  motorFino: { label: "Motor fino", emoji: "✋", color: "#8fbf9f" },
  motorGrosso: { label: "Motor grosso", emoji: "🏃", color: "#8db4d9" },
  cognitivo: { label: "Pensar", emoji: "🧩", color: "#c9a0dc" },
  social: { label: "Faz de conta", emoji: "🧸", color: "#f0a1a1" },
};

window.ACTIVITIES = [
  // ===== 2 anos (18 a 42 meses) =====
  {
    id: "caca-cores",
    band: "dois",
    domain: "cognitivo",
    title: "Caça às cores pela casa",
    summary: "Escolha uma cor e saiam procurando coisas dessa cor. Nomear e agrupar é a base de classificar.",
    materials: ["Nada além da casa", "Opcional: uma sacola para guardar os achados"],
    steps: [
      "Mostre um objeto vermelho e diga: \"vermelho\". Peça: \"vamos achar mais vermelho?\"",
      "Ande com {ela} pela casa. Quando {ela} apontar algo, nomeie: \"a almofada vermelha!\"",
      "Junte os achados no chão. Conte junto: \"um, dois, três\".",
      "Troque para outra cor só se {ela} ainda estiver interessada.",
      "Feche guardando tudo no lugar, nomeando cada objeto de novo.",
    ],
    observe: ["{Ela} aponta ou traz objetos da cor certa?", "Repete o nome da cor?", "Segue você por vários cômodos?"],
    words: "vermelho, azul, amarelo, igual, mais, achei",
  },
  {
    id: "torre-potes",
    band: "dois",
    domain: "motorFino",
    title: "Torre de potes",
    summary: "Empilhar potes de tamanhos diferentes treina coordenação, noção de tamanho e tolerância a frustração.",
    materials: ["4 a 6 potes plásticos de cozinha de tamanhos diferentes", "Chão ou tapete"],
    steps: [
      "Espalhe os potes. Empilhe dois e diga: \"em cima\". Derrube rindo: \"caiu!\"",
      "Entregue um pote a {ela} e espere. Não corrija a ordem no começo.",
      "Quando cair, nomeie: \"caiu, vamos de novo\". A queda é parte do jogo.",
      "Depois experimente encaixar um dentro do outro: \"grande, pequeno\".",
      "Termine guardando os potes no armário com {ela}.",
    ],
    observe: ["Empilha 4 ou mais sem ajuda?", "Tenta de novo depois de cair?", "Distingue grande e pequeno quando você pede?"],
    words: "em cima, caiu, grande, pequeno, dentro, de novo",
  },
  {
    id: "livro-perguntas",
    band: "dois",
    domain: "linguagem",
    title: "Livro com perguntas",
    summary: "Ler não é só narrar. Perguntar e esperar a resposta é o que mais faz o vocabulário crescer.",
    materials: ["Um livro de figuras que {ela} goste", "Colo"],
    steps: [
      "Deixe {ela} escolher o livro e virar as páginas, mesmo fora de ordem.",
      "Em cada página, aponte e pergunte: \"o que é isso?\". Espere 5 segundos.",
      "Se {ela} falar, expanda: \"cachorro\" vira \"é, o cachorro marrom está dormindo\".",
      "Se não falar, você nomeia e segue. Sem cobrar.",
      "Peça ações: \"cadê o gato? mostra o gato\".",
    ],
    observe: ["Aponta figuras quando você nomeia?", "Fala palavras novas do livro?", "Junta duas palavras (\"gato dormindo\")?"],
    words: "cadê, esse, aquele, dormindo, comendo, grande",
  },
  {
    id: "circuito-almofadas",
    band: "dois",
    domain: "motorGrosso",
    title: "Circuito de almofadas",
    summary: "Subir, pular e passar por baixo. Equilíbrio e planejamento do corpo, com muito riso.",
    materials: ["Almofadas e travesseiros", "Uma cadeira para passar por baixo", "Espaço livre"],
    steps: [
      "Monte um caminho: almofadas para pisar, cadeira para passar embaixo, travesseiro para pular.",
      "Faça você primeiro, narrando: \"em cima, embaixo, pula!\"",
      "Vá junto segurando a mão nas partes mais altas.",
      "Depois de algumas voltas, deixe {ela} mudar o circuito.",
      "Encerre com uma \"chegada\" e um abraço.",
    ],
    observe: ["Pula com os dois pés fora do chão?", "Sobe em superfícies baixas {sozinha}?", "Segue a sequência do caminho?"],
    words: "em cima, embaixo, pula, devagar, rápido, chegou",
  },
  {
    id: "cozinha-boneca",
    band: "dois",
    domain: "social",
    title: "Comidinha para o ursinho",
    summary: "Faz de conta é pensamento simbólico: um bloco vira comida. É também treino de cuidado e sequência.",
    materials: ["Um boneco ou bicho de pelúcia", "Pratinhos, colher, potes vazios"],
    steps: [
      "Diga: \"o ursinho está com fome. Vamos fazer comida?\"",
      "Finja mexer uma panela. Ofereça a {ela} a colher.",
      "Dê de comer ao ursinho e comente: \"hmm, gostoso! ele quer mais?\"",
      "Proponha o próximo passo: \"agora ele vai dormir? cadê o cobertor?\"",
      "Deixe {ela} conduzir. Siga a história {dela}, por mais estranha.",
    ],
    observe: ["Usa um objeto como se fosse outro?", "Dá de comer, cobre ou nina o boneco?", "Fala pelo boneco?"],
    words: "fome, comer, mais, dormir, cobertor, gostoso",
  },
  {
    id: "musica-corpo",
    band: "dois",
    domain: "linguagem",
    title: "Música com partes do corpo",
    summary: "Cantar e apontar une ritmo, vocabulário e imitação. Funciona melhor quando você exagera os gestos.",
    materials: ["Sua voz", "Opcional: um espelho"],
    steps: [
      "Cante \"cabeça, ombro, joelho e pé\" bem devagar, tocando cada parte.",
      "Pare antes da última palavra e espere {ela} completar.",
      "Peça: \"cadê o seu nariz? e o nariz do vovô?\"",
      "Acelere aos poucos. Erre de propósito e deixe {ela} corrigir.",
      "Termine com uma versão bem lenta, quase sussurrada.",
    ],
    observe: ["Aponta 6 ou mais partes do corpo?", "Completa palavras da música?", "Imita os gestos?"],
    words: "cabeça, barriga, mão, pé, nariz, boca",
  },
  {
    id: "massinha",
    band: "dois",
    domain: "motorFino",
    title: "Massinha caseira",
    summary: "Apertar, esticar e cortar fortalece a mão que vai segurar o lápis. Fazer a massa juntos já é a brincadeira.",
    materials: ["2 xícaras de farinha, 1 de sal, 1 de água, 1 colher de óleo", "Opcional: corante de alimento"],
    steps: [
      "Misturem os ingredientes juntos. Deixe {ela} despejar e mexer, mesmo que suje.",
      "Mostre: apertar, fazer bolinha, fazer cobrinha.",
      "Esconda um objeto pequeno dentro e peça para achar.",
      "Corte com faca de plástico ou tampa. Nomeie: \"cortou, dois pedaços\".",
      "Guarde em pote fechado. Dura uma semana na geladeira.",
    ],
    observe: ["Usa as duas mãos juntas?", "Consegue fazer uma bolinha, mesmo torta?", "Fica na atividade por 5 minutos ou mais?"],
    words: "apertar, mole, bolinha, cobrinha, cortar, pedaço",
  },
  {
    id: "rabisco-gigante",
    band: "dois",
    domain: "motorFino",
    title: "Rabisco gigante no chão",
    summary: "Papel grande no chão e giz de cera grosso. Linhas, círculos e a descoberta de que o gesto deixa marca.",
    materials: ["Papel pardo ou o verso de um cartaz, preso no chão com fita", "Giz de cera grosso"],
    steps: [
      "Faça uma linha longa e diga: \"reta\". Depois um círculo: \"redondo\".",
      "Entregue o giz e só observe por um minuto.",
      "Desenhe algo simples e pergunte: \"o que é?\". Aceite qualquer resposta.",
      "Peça: \"faz uma linha bem grande\" e comemore o gesto, não o resultado.",
      "Pendure o papel na parede na altura {dela}.",
    ],
    observe: ["Segura o giz com os dedos ou com o punho fechado?", "Imita uma linha vertical?", "Diz o que desenhou?"],
    words: "reta, redondo, grande, pequeno, cor, meu",
  },
  {
    id: "bola-alvo",
    band: "dois",
    domain: "motorGrosso",
    title: "Bola no balde",
    summary: "Chutar e arremessar com alvo. Planejar o movimento e aceitar errar.",
    materials: ["Uma bola macia", "Um balde, caixa ou cesto"],
    steps: [
      "Coloque o balde perto. Mostre: jogar a bola dentro. \"Entrou!\"",
      "Entregue a bola. Comemore tentativas, não acertos.",
      "Afaste o balde um pouco a cada rodada.",
      "Troque para chutar: coloque a bola no chão e chute devagar.",
      "Encerre guardando a bola no balde.",
    ],
    observe: ["Chuta a bola para frente sem cair?", "Arremessa por cima da cabeça?", "Tenta de novo depois de errar?"],
    words: "joga, chuta, entrou, longe, perto, de novo",
  },
  {
    id: "cade-objeto",
    band: "dois",
    domain: "cognitivo",
    title: "Cadê? Esconde-esconde de objetos",
    summary: "Esconder um brinquedo embaixo de 3 copos. Memória, atenção e a alegria de acertar.",
    materials: ["3 copos ou potes opacos", "Um brinquedo pequeno"],
    steps: [
      "Mostre o brinquedo, esconda embaixo de um copo na frente {dela}. \"Cadê?\"",
      "Deixe {ela} levantar. Comemore junto.",
      "Passe a trocar os copos de lugar devagar, ainda com {ela} olhando.",
      "Inverta: peça que {ela} esconda para você achar. Erre de propósito às vezes.",
      "Termine com o brinquedo \"dormindo\" embaixo do copo.",
    ],
    observe: ["Lembra em qual copo está depois de trocar?", "Esconde e espera você procurar?", "Diz \"cadê\" ou \"achei\"?"],
    words: "cadê, achei, embaixo, esse, aqui, não",
  },
  {
    id: "banho-experimentos",
    band: "dois",
    domain: "cognitivo",
    title: "Experimentos no banho",
    summary: "Encher, despejar, afundar, boiar. Ciência de verdade com potes e água.",
    materials: ["Potes, copos, funil, uma esponja", "Banheira ou bacia"],
    steps: [
      "Dê dois potes. Encha um e despeje no outro: \"cheio, vazio\".",
      "Pergunte: \"a esponja afunda?\". Testem. \"Boiou!\"",
      "Aperte a esponja cheia e nomeie: \"espremeu, saiu água\".",
      "Peça para {ela} encher um pote e entregar para você.",
      "Feche esvaziando tudo juntos: \"acabou a água\".",
    ],
    observe: ["Despeja de um pote no outro sem derramar tudo?", "Antecipa o que vai acontecer?", "Repete \"cheio\" e \"vazio\"?"],
    words: "cheio, vazio, afundou, boiou, molhado, acabou",
  },
  {
    id: "telefone-familia",
    band: "dois",
    domain: "social",
    title: "Telefone de brinquedo com a família",
    summary: "Fingir que liga para a mãe, a tia, o vovô. Vocabulário de pessoas e prática de turnos de conversa.",
    materials: ["Um telefone de brinquedo ou uma caixinha", "Opcional: o álbum falante deste app, para ver as fotos antes"],
    steps: [
      "Ligue você primeiro: \"alô, é a tia Ana? Está tudo bem?\". Passe o telefone: \"{ela} quer falar com você\".",
      "Espere {ela} falar qualquer coisa. Responda como se fosse a pessoa.",
      "Pergunte: \"quem mais vamos ligar?\". Deixe {ela} escolher.",
      "Inclua o cachorro, o ursinho. Quanto mais absurdo, melhor.",
      "Encerre com \"tchau, beijo\" e desligue com gesto.",
    ],
    observe: ["Fala e depois espera a resposta?", "Nomeia pessoas da família?", "Usa \"alô\" e \"tchau\" no contexto?"],
    words: "alô, tchau, quem, tia, vovó, beijo",
  },
  {
    id: "ajudante-casa",
    band: "dois",
    domain: "social",
    title: "Ajudante da casa",
    summary: "Guardar meias, colocar guardanapos, regar planta. Tarefas reais são as brincadeiras que {ela} mais valoriza.",
    materials: ["Uma tarefa simples e segura de verdade", "Paciência para demorar o triplo"],
    steps: [
      "Escolha uma tarefa: separar meias da roupa limpa, por exemplo.",
      "Mostre uma vez, devagar, nomeando: \"meia do papai, meia {de} {nome}\".",
      "Deixe {ela} fazer. Não refaça na frente {dela}.",
      "Comente o que {ela} faz: \"você colocou na gaveta\". Sem \"muito bem\" a toda hora.",
      "Agradeça de verdade e mostre o resultado: \"olha, tudo guardado\".",
    ],
    observe: ["Segue instruções de dois passos (\"pega a meia e põe na gaveta\")?", "Pareia objetos iguais?", "Insiste em fazer {sozinha}?"],
    words: "ajudar, guardar, igual, do papai, meu, pronto",
  },
  {
    id: "passeio-nomes",
    band: "dois",
    domain: "linguagem",
    title: "Passeio dos nomes",
    summary: "Uma volta no quarteirão nomeando tudo. Ao ar livre, com movimento, é onde {ela} mais fala.",
    materials: ["Uma rua tranquila ou praça", "Tempo sem pressa"],
    steps: [
      "Deixe {ela} decidir a direção quando for seguro.",
      "Nomeie o que {ela} olha, não o que você acha importante: \"pedra, formiga, portão\".",
      "Pare e escute sons: \"o que é isso? um passarinho\".",
      "Peça para {ela} levar algo achado (folha, pedra) para casa.",
      "Em casa, mostre o achado para outra pessoa e deixe {ela} contar.",
    ],
    observe: ["Aponta e pergunta \"o que é?\"", "Anda 10 minutos sem pedir colo?", "Conta para outra pessoa o que viu?"],
    words: "olha, pedra, folha, passarinho, carro, casa",
  },
  {
    id: "quebra-cabeca-foto",
    band: "dois",
    domain: "cognitivo",
    title: "Quebra-cabeça de foto",
    summary: "Uma foto grande da família colada em papelão e cortada em 2 ou 3 partes. Aos 2 anos, peças grandes e poucas: o que se treina é ver o todo a partir das partes.",
    materials: ["Uma foto impressa em tamanho A4 ou maior (rosto de alguém querido funciona melhor)", "Papelão de caixa e cola", "Tesoura"],
    steps: [
      "Cole a foto no papelão. Mostre inteira e nomeie: \"olha o vovô!\". Deixe {ela} olhar bastante.",
      "Corte em 2 partes na frente {dela}, com um corte reto ou levemente curvo. \"Cortei! Cadê o vovô?\"",
      "Separe as partes um pouco e espere. Se {ela} não juntar, junte devagar e diga \"voltou!\".",
      "Repita várias vezes. Depois de alguns dias, corte uma das partes de novo, para 3 peças.",
      "Guarde as peças num envelope com a foto inteira desenhada fora, para {ela} achar sozinha.",
    ],
    observe: ["Vira a peça para encaixar?", "Junta 2 partes sem ajuda?", "Fala o nome de quem está na foto quando monta?"],
    words: "cadê, achou, encaixa, vira, junto, inteiro",
  },
  {
    id: "contar-de-verdade",
    band: "dois",
    domain: "cognitivo",
    title: "Contar de verdade",
    summary: "Contar degraus, dedos, colheres: um número por toque. Aos 2 anos o objetivo é a cantilena \"um, dois, três\" e a ideia de um por vez, não a quantidade.",
    materials: ["Coisas do dia a dia em pequena quantidade: 3 frutas, 3 degraus, 3 blocos", "Sua mão para tocar junto"],
    steps: [
      "Nos degraus: suba tocando cada um com o pé e conte alto: \"um, dois, três\". Repita todo dia.",
      "Na mesa: ponha 3 frutas. Toque uma por vez com o dedo {dela} sobre o seu: \"um, dois, três. Três bananas!\"",
      "Brinque de \"um, dois, três, já!\" para correr, pular, jogar a bola. A pausa antes do \"já\" é o que {ela} mais gosta.",
      "Peça \"me dá um\" e depois \"me dá mais\". Um versus muitos vem antes de qualquer número.",
      "Cante músicas com números (\"um, dois, feijão com arroz\") apontando nos dedos.",
    ],
    observe: ["Recita \"um, dois, três\" mesmo fora de ordem?", "Toca um objeto por número ou passa por cima?", "Entende \"um\" e \"mais\" quando você pede?"],
    words: "um, dois, três, mais, um só, já",
  },
  {
    id: "caixa-de-encaixe",
    band: "dois",
    domain: "motorFino",
    title: "Caixa de encaixe caseira",
    summary: "Uma caixa de sapato com dois furos: um redondo e um quadrado. Encaixar é discriminar forma, girar o punho e persistir.",
    materials: ["Caixa de sapato com tampa", "Estilete (só o adulto) para 2 furos: redondo e quadrado", "Tampas redondas de pote e blocos quadrados que caibam"],
    steps: [
      "Faça os dois furos na tampa, com folga. Mostre uma tampa redonda passando pelo furo redondo: \"entrou!\"",
      "Entregue uma peça e espere. Se {ela} tentar o furo errado, só diga \"não coube, tenta o outro\".",
      "Quando encaixar, nomeie a forma: \"redondo!\". O nome vem depois do sucesso, não antes.",
      "Abra a caixa e despeje tudo. Recomeçar é metade da graça.",
      "Semanas depois, acrescente um furo triangular. Um por vez.",
    ],
    observe: ["Distingue redondo de quadrado sem tentar todos?", "Gira a peça para caber?", "Insiste depois de errar?"],
    words: "redondo, quadrado, entrou, não coube, gira, de novo",
  },
  {
    id: "encaixe-tampas",
    band: "dois",
    domain: "motorFino",
    title: "Tampas e potes",
    summary: "Achar a tampa certa de cada pote e rosquear. Pareamento e rotação do punho.",
    materials: ["4 ou 5 potes com tampa de rosca de tamanhos diferentes", "Uma bandeja"],
    steps: [
      "Espalhe potes e tampas separados. Mostre um encaixe: \"essa é dessa\".",
      "Deixe {ela} tentar. Erros são parte: \"não coube, tenta outra\".",
      "Mostre o rosquear devagar, com a mão {dela} sobre a sua.",
      "Guarde um botão dentro de um pote e chacoalhe: \"onde está o barulho?\"",
      "Feche todos os potes e guarde na bandeja.",
    ],
    observe: ["Pareia tampa e pote pelo tamanho?", "Gira o punho para rosquear?", "Persiste depois de errar?"],
    words: "tampa, abre, fecha, gira, cabe, não cabe",
  },
];

// Marcos 24 e 30 meses (CDC 2022, itens que 75% ou mais das crianças fazem na idade).
window.MILESTONES = [
  // ===== 2 anos =====
  {
    group: "Social e emocional",
    band: "dois",
    items: [
      { id: "s1", age: 24, text: "Percebe quando alguém está triste ou machucado (para, olha, parece {preocupada})" },
      { id: "s2", age: 24, text: "Olha para o seu rosto para ver como reagir a uma situação nova" },
      { id: "s3", age: 30, text: "Brinca ao lado de outras crianças e às vezes junto com elas" },
      { id: "s4", age: 30, text: "Mostra o que consegue fazer dizendo \"olha!\"" },
      { id: "s5", age: 30, text: "Segue rotinas simples quando pedido, como guardar brinquedos" },
    ],
  },
  {
    group: "Linguagem e comunicação",
    band: "dois",
    items: [
      { id: "l1", age: 24, text: "Aponta para coisas no livro quando você pergunta (\"cadê o urso?\")" },
      { id: "l2", age: 24, text: "Fala pelo menos duas palavras juntas (\"mais leite\")" },
      { id: "l3", age: 24, text: "Aponta para pelo menos duas partes do corpo quando você pede" },
      { id: "l4", age: 24, text: "Usa mais gestos além de apontar e acenar, como mandar beijo ou fazer \"sim\" com a cabeça" },
      { id: "l5", age: 30, text: "Fala cerca de 50 palavras" },
      { id: "l6", age: 30, text: "Fala duas ou mais palavras com uma ação (\"cachorro correndo\")" },
      { id: "l7", age: 30, text: "Nomeia coisas no livro quando você aponta" },
      { id: "l8", age: 30, text: "Usa \"eu\", \"meu\", \"nós\"" },
    ],
  },
  {
    group: "Cognitivo",
    band: "dois",
    items: [
      { id: "c1", age: 24, text: "Segura algo em uma mão enquanto usa a outra (tira a tampa segurando o pote)" },
      { id: "c2", age: 24, text: "Tenta usar botões, maçanetas ou interruptores" },
      { id: "c3", age: 24, text: "Brinca com mais de um brinquedo ao mesmo tempo (põe comida no prato do boneco)" },
      { id: "c4", age: 30, text: "Usa objetos para fingir, como dar de comer a um boneco com um bloco" },
      { id: "c5", age: 30, text: "Resolve problemas simples, como subir num banquinho para alcançar" },
      { id: "c6", age: 30, text: "Segue instruções de dois passos (\"pega o sapato e põe no cesto\")" },
      { id: "c7", age: 30, text: "Sabe pelo menos uma cor, apontando quando você pede" },
    ],
  },
  {
    group: "Movimento",
    band: "dois",
    items: [
      { id: "m1", age: 24, text: "Chuta uma bola" },
      { id: "m2", age: 24, text: "Corre" },
      { id: "m3", age: 24, text: "Sobe alguns degraus com ou sem ajuda" },
      { id: "m4", age: 24, text: "Come com colher" },
      { id: "m5", age: 30, text: "Usa as mãos para girar coisas, como maçanetas e tampas" },
      { id: "m6", age: 30, text: "Tira algumas roupas {sozinha}, como calça folgada ou casaco aberto" },
      { id: "m7", age: 30, text: "Pula com os dois pés saindo do chão" },
      { id: "m8", age: 30, text: "Vira páginas de um livro, uma de cada vez" },
    ],
  },
];

// Frases curtas de transição para o fim da sessão do álbum.
window.END_ACTIVITIES = [
  { title: "Vamos achar o vovô de verdade?", summary: "Ou ligar para quem apareceu no álbum. Deixe {ela} dizer o nome antes de discar." },
  { title: "Cadê o cachorro?", summary: "Procurem o bicho que apareceu na foto, ou um desenho dele em um livro." },
  { title: "Torre de potes", summary: "Quatro potes da cozinha e chão livre. Empilhar e derrubar já é o jogo." },
  { title: "Passeio dos nomes", summary: "Uma volta no quintal ou na rua nomeando tudo o que {ela} olhar." },
  { title: "Música com o corpo", summary: "Cabeça, ombro, joelho e pé, bem devagar, apontando em você e {nela}." },
];

// ===== Faixas etárias =====
// "bebe": 0 a 14 meses (conteúdo escrito para 0 a 6). "dois": 15 a 42 meses (conteúdo escrito para 24 a 30).
window.AGE_BANDS = {
  bebe: { label: "Bebê", min: 0, max: 14, screens: false,
    note: "Nenhuma tela antes dos 2 anos, nem de fundo (SBP, OMS, AAP). Nessa fase o que desenvolve é rosto, voz e colo." },
  dois: { label: "Faixa dos 2 anos", min: 15, max: 42, screens: true,
    note: "Até 1 hora de tela por dia, sempre com um adulto participando (SBP, OMS)." },
};

window.TIPS = {
  bebe: [
    "<strong>Rosto a 25 cm.</strong> É a distância em que o bebê enxerga melhor até uns 3 meses. Fale, sorria e espere a resposta.",
    "<strong>Responda a cada som.</strong> Quando o bebê balbucia e você responde, ele aprende que a voz dele tem efeito. É a base da linguagem.",
    "<strong>TV desligada de fundo.</strong> Mesmo sem o bebê olhar, TV ligada reduz em até 20% o quanto os adultos falam com ele.",
    "<strong>Barriga para cima para dormir, de bruços para brincar.</strong> Tempo de bruços acordado e vigiado fortalece pescoço e tronco.",
  ],
  dois: [
    "<strong>{Ela} aprende de você, não da tela.</strong> Até uns 3 anos a criança absorve muito menos de vídeos e apps do que de uma pessoa ao vivo.",
    "<strong>Fale, nomeie, espere.</strong> Nomear o que {ela} olha e dar 5 segundos para {ela} responder é o que mais expande vocabulário.",
    "<strong>Repetir é bom.</strong> A mesma brincadeira 10 vezes é aprendizado, não tédio.",
    "<strong>Sem pressa e sem prêmio.</strong> O interesse {dela} é o combustível. Se {ela} largar, tudo bem.",
  ],
};

// ===== Bebê (2 a 6 meses) =====
window.ACTIVITIES.push(
  {
    id: "b-brucos",
    band: "bebe",
    domain: "motorGrosso",
    title: "Tempo de bruços",
    summary: "Alguns minutos de bruços, acordado e com você na frente. Fortalece pescoço, ombros e tronco, e previne achatamento da cabeça.",
    materials: ["Um tapete ou manta firme no chão", "Seu rosto na altura do bebê", "Opcional: um chocalho ou pano colorido"],
    steps: [
      "Deite o bebê de bruços no chão, nunca em cama ou sofá. Deite-se de frente para {ela}.",
      "Fale e sorria na altura dos olhos {dela}. Isso motiva a levantar a cabeça.",
      "Comece com 1 a 2 minutos. Se chorar, vire de barriga para cima, acalme e tente depois.",
      "Repita 3 ou 4 vezes ao dia, sempre depois da troca de fralda, por exemplo.",
      "Mova um chocalho devagar de um lado para o outro para {ela} acompanhar com os olhos.",
    ],
    observe: ["Levanta a cabeça por alguns segundos (2 meses)?", "Apoia nos antebraços e levanta o peito (4 meses)?", "Vira a cabeça para os dois lados?"],
    words: "olha, cabeça, força, aqui, vovô, vem",
  },
  {
    id: "b-conversa",
    band: "bebe",
    domain: "linguagem",
    title: "Conversa cara a cara",
    summary: "Você fala, espera, o bebê responde com som ou gesto, você responde de volta. Esse vai-e-volta é o exercício mais poderoso dos primeiros meses.",
    materials: ["Colo ou bebê deitado de frente", "Uns 5 minutos de calma"],
    steps: [
      "Fique a uns 25 cm do rosto {dela}. Chame pelo nome e sorria.",
      "Diga uma frase curta e espere 5 segundos. Olhe nos olhos.",
      "Quando {ela} fizer um som, imite de volta e acrescente: \"aaah, é mesmo? me conta\".",
      "Varie o tom: grave, agudo, sussurro. Observe a reação.",
      "Encerre quando {ela} desviar o olhar. É o sinal de que cansou.",
    ],
    observe: ["Olha para o seu rosto e sustenta o olhar?", "Faz sons além de choro (2 meses)?", "Responde com sons quando você fala (4 meses)?"],
    words: "oi, olha, sim, é, gostou, mais",
  },
  {
    id: "b-cantar",
    band: "bebe",
    domain: "social",
    title: "Cantar embalando",
    summary: "Cantar no colo, com balanço lento, regula o bebê e ensina ritmo e melodia da língua antes das palavras.",
    materials: ["Sua voz, afinada ou não", "Uma cadeira confortável"],
    steps: [
      "Segure o bebê no colo com o rosto voltado para o seu.",
      "Cante uma música curta, bem devagar, sempre a mesma. Repetição é o que funciona.",
      "Balance no ritmo. Mude para sussurro no final.",
      "Faça uma pausa antes da última palavra e olhe para {ela}. Com o tempo {ela} vai antecipar.",
      "Use a mesma música antes de dormir para virar um sinal de rotina.",
    ],
    observe: ["Acalma quando você canta ou fala (2 meses)?", "Sorri de volta quando você sorri?", "Dá risadinhas (4 meses)?"],
    words: "nana, calma, dorme, colo, canta, tchau",
  },
  {
    id: "b-rastrear",
    band: "bebe",
    domain: "cognitivo",
    title: "Seguir com os olhos",
    summary: "Mover um objeto contrastante devagar para o bebê acompanhar. Treina foco, coordenação dos olhos e atenção.",
    materials: ["Um objeto de cor forte ou preto e branco (chocalho, meia, cartão)", "Bebê deitado de barriga para cima"],
    steps: [
      "Mostre o objeto a uns 25 cm dos olhos até {ela} fixar.",
      "Mova bem devagar para um lado, pare, volte ao centro. Depois para o outro lado.",
      "Suba e desça. Fale enquanto move: \"olha, foi para lá\".",
      "Faça um círculo lento. Pare quando {ela} perder o interesse.",
      "Termine deixando o objeto na mão {dela} para segurar (a partir de 3 meses).",
    ],
    observe: ["Segue o objeto de um lado ao outro?", "Olha para o objeto por vários segundos?", "Tenta alcançar com a mão (4 meses)?"],
    words: "olha, foi, voltou, ali, pega, cadê",
  },
  {
    id: "b-massagem",
    band: "bebe",
    domain: "motorFino",
    title: "Massagem nomeando o corpo",
    summary: "Toque firme e lento nomeando cada parte. Consciência corporal, vínculo e vocabulário que entra pelo tato.",
    materials: ["Óleo vegetal próprio para bebê, opcional", "Ambiente aquecido, depois do banho"],
    steps: [
      "Deite o bebê de barriga para cima e peça licença: \"vou fazer massagem?\". Espere a reação.",
      "Passe as mãos das coxas aos pés, nomeando: \"perna, pé, dedinhos\".",
      "Braços: do ombro à mão. Abra a mão {dela} e toque cada dedo.",
      "Barriga em círculos no sentido do relógio. \"Barriga\".",
      "Termine com o rosto: testa, bochechas. Pare se {ela} chorar ou virar o rosto.",
    ],
    observe: ["Abre as mãos por alguns instantes (2 meses)?", "Leva as mãos à boca (4 meses)?", "Relaxa ou se agita com o toque?"],
    words: "perna, pé, mão, barriga, rosto, calma",
  },
  {
    id: "b-espelho",
    band: "bebe",
    domain: "social",
    title: "Espelho e caretas",
    summary: "Bebê no colo diante do espelho, você fazendo caretas e sons. Imitação e reconhecimento de rostos.",
    materials: ["Um espelho seguro, fixo", "Colo"],
    steps: [
      "Sente-se de frente para o espelho com o bebê no colo, virado para o espelho.",
      "Aponte e diga: \"olha {ela}! e o vovô!\".",
      "Faça uma careta lenta: língua para fora, boca bem aberta. Espere.",
      "Mude de expressão com som: \"ooo\", \"aaa\". Repita a que mais {ela} olhar.",
      "Encerre com um sorriso longo e um \"tchau\" acenando no espelho.",
    ],
    observe: ["Olha fixo para os rostos no espelho?", "Imita abrir a boca ou pôr a língua para fora?", "Sorri para chamar atenção (4 meses)?"],
    words: "olha, careta, língua, boca, tchau, sorriso",
  },
  {
    id: "b-texturas",
    band: "bebe",
    domain: "cognitivo",
    title: "Passeio das texturas",
    summary: "Encostar mãos e pés do bebê em superfícies diferentes, nomeando. Exploração sensorial guiada, sem pressa.",
    materials: ["Coisas da casa: toalha felpuda, folha de planta, colher fria, manta macia", "Bebê no colo"],
    steps: [
      "Segure o bebê no colo e leve a mão {dela} até uma toalha: \"macio\".",
      "Depois uma colher limpa e fria: \"frio\". Observe o rosto.",
      "Pé em uma folha de planta: \"cócegas\". Ria junto.",
      "Duas ou três texturas por vez bastam. Repita nos próximos dias com outras.",
      "Termine com o toque mais gostoso, a manta ou o seu rosto.",
    ],
    observe: ["Reage diferente a texturas diferentes?", "Fecha a mão em torno do objeto (a partir de 3 meses)?", "Mantém atenção por alguns segundos?"],
    words: "macio, frio, quente, áspero, gostoso, mão",
  }
);

// ===== Marcos 2 e 4 meses (CDC 2022) =====
window.MILESTONES.push(
  {
    group: "Social e emocional",
    band: "bebe",
    items: [
      { id: "bs1", age: 2, text: "Acalma quando alguém fala ou pega no colo" },
      { id: "bs2", age: 2, text: "Olha para o seu rosto" },
      { id: "bs3", age: 2, text: "Parece feliz ao ver você se aproximar" },
      { id: "bs4", age: 2, text: "Sorri quando você fala ou sorri" },
      { id: "bs5", age: 4, text: "Sorri por conta própria para chamar sua atenção" },
      { id: "bs6", age: 4, text: "Dá risadinhas quando você tenta fazer rir" },
      { id: "bs7", age: 4, text: "Olha, se mexe ou faz sons para conseguir ou manter sua atenção" },
    ],
  },
  {
    group: "Linguagem e comunicação",
    band: "bebe",
    items: [
      { id: "bl1", age: 2, text: "Faz sons além de choro" },
      { id: "bl2", age: 2, text: "Reage a sons altos" },
      { id: "bl3", age: 4, text: "Faz sons como \"ooo\" e \"aaa\"" },
      { id: "bl4", age: 4, text: "Responde com sons quando você fala" },
      { id: "bl5", age: 4, text: "Vira a cabeça na direção da sua voz" },
    ],
  },
  {
    group: "Cognitivo",
    band: "bebe",
    items: [
      { id: "bc1", age: 2, text: "Acompanha você com os olhos quando você se move" },
      { id: "bc2", age: 2, text: "Olha para um brinquedo por vários segundos" },
      { id: "bc3", age: 4, text: "Abre a boca ao ver o peito ou a mamadeira quando está com fome" },
      { id: "bc4", age: 4, text: "Olha para as próprias mãos com interesse" },
    ],
  },
  {
    group: "Movimento",
    band: "bebe",
    items: [
      { id: "bm1", age: 2, text: "Levanta a cabeça quando está de bruços" },
      { id: "bm2", age: 2, text: "Mexe os dois braços e as duas pernas" },
      { id: "bm3", age: 2, text: "Abre as mãos por alguns instantes" },
      { id: "bm4", age: 4, text: "Segura a cabeça firme sem apoio quando está no colo" },
      { id: "bm5", age: 4, text: "Segura um brinquedo quando você coloca na mão" },
      { id: "bm6", age: 4, text: "Usa o braço para bater em brinquedos" },
      { id: "bm7", age: 4, text: "Leva as mãos à boca" },
      { id: "bm8", age: 4, text: "Apoia nos antebraços quando está de bruços" },
    ],
  }
);
